sudo: required

services:
- docker

language: go

go:
- "1.x"

script:
- make docker

deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - DOCKER_ID_USER="$DOCKER_USERNAME" make pushimage
  on:
    branch: master
