sudo: required

services:
- docker

language: go

go:
- "1.x"

env:
  GO111MODULE: "on"

script:
- make docker

deploy:
  provider: script
  script: bash scripts/docker-push.sh
  on:
    branch: master
