# Needed to use Docker
# https://docs.travis-ci.com/user/docker/
#sudo: required
#
#services:
#- docker

language: go

go:
- "1.x"

jobs:
  include:
    # Build binary + image on Linux
    - stage: test
      script: make docker
      os: linux
    # Only build binary on Windows
    - stage: test
      script: go build ./...
      os: windows
#    - stage: deploy
#      name: "Deploy image to Docker Hub"
#      provider: script
#      script: bash scripts/docker-push.sh
#      on:
#        branch: master
