# Needed to use Docker
# https://docs.travis-ci.com/user/docker/
sudo: required

services:
- docker

language: go

go:
- "1.x"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
        go build ./...
      else
        make docker
      fi
    )

matrix:
  include:
    - stage: test
      os: linux
    - stage: test
      os: windows
    - stage: deploy
      name: "Deploy image to Docker Hub"
      provider: script
      script: bash scripts/docker-push.sh
      on:
        branch: master
      os: linux
