version: 2.1

commands:
  setup_environment:
    description: |
      Setup the minimal environment for the CI.
    steps:
    - checkout
    - run: go version
    - run: go env
    - run: make promu

jobs:
  build:
    description: |
      Cross-build and store the binaries.
    machine:
      enabled: true
    steps:
    - setup_environment
    - run: promu crossbuild -v
    - persist_to_workspace:
        paths:
        - .build
        root: .
    - store_artifacts:
        destination: /build
        path: .build

workflows:
  version: 2
  prometheus:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
